- platform: mqtt
  name: "Droger verbruik vandaag"
  state_topic: "droger/sonoff/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Droger verbruik gisteren"
  state_topic: "droger/sonoff/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Droger verbruik totaal"
  state_topic: "droger/sonoff/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Droger verbruik"
  state_topic: "droger/sonoff/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"