- platform: sabnzbd
  host: 192.168.2.100
  port: 19820
  api_key: e44754c6cd4090d5751443bccbbd5067
  monitored_variables:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'
    - 'queue_count'