- platform: mqtt
  command_topic: "espItho/Itho/cmd"
  state_topic : "espItho/Itho/State"
  speed_command_topic: "espItho/Itho/cmd"
  speed_state_topic: "espItho/Itho/State"
  state_value_template: "{% if value|float==0 %}State 0{% endif %}{% if value|float >0 %}State 1{% endif %}"
  speed_value_template: "{% if value|float==0 %}State 0{% endif %}{% if value|float >0 and value|float <=4 %}State {{value}}{% endif %}{% if value|float >=11 %}State 3{% endif %}"
  payload_on: "State 1"
  payload_off: "State 0"
  payload_low_speed: "State 1"
  payload_medium_speed: "State 2"
  payload_high_speed: "State 3"
  optimistic: "true"
  name: Mechanische ventilatie
  speeds:
    - low
    - medium
    - high  
  