- alias: 'Alie skyradio'
  initial_state: true
  hide_entity: False
  trigger:
    - platform: state
      entity_id: person.alie
      from: 'not_home'
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: person.jan
        state: 'not_home'
      - condition: state
        entity_id: person.manon
        state: 'not_home'
  action:
    - delay:
        seconds: 30
    - service: remote.turn_on
      entity_id: remote.woonkamer
      data:
        activity: 'Radio'
    - service: notify.jan
      data:
        title: "Radio aangezet voor Alie"
        message: "Alie is alleen thuis. Radio op skyradio gezet"    
     