- alias: "Cube rotate - Veranda ledstrip snelheid"
  initial_state: true
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028779a2
      action_type: rotate
  condition:
    - condition: state
      entity_id: light.ledstrip_veranda
      state: 'on'
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.ledStrip1_animatie_snelheid
      value: >
          {% set state =  trigger.event.data.action_value | int  -%}
            {%-  if state > -10 and state < 10 -%}
                {%- set state  =0 -%}
            {%- endif %}
            {{ states.input_number.ledStrip1_animatie_snelheid.state | int + state }}  

- alias: "Cube flip - Verander effect vooruit"
  initial_state: true
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028779a2
      action_type: flip180
  condition:
    - condition: state
      entity_id: light.ledstrip_veranda
      state: 'on'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.ledstrip_veranda
      effect: >
        {% for x in states.light.ledstrip_veranda.attributes.effect_list %}
          {% if x == states.light.ledstrip_veranda.attributes.effect %}
          {{states.light.ledstrip_veranda.attributes.effect_list[loop.index0+1] }}
          {% endif %}
        {% endfor %}

- alias: "Cube flip - Verander effect acheruit"
  initial_state: 'on'
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028779a2
      action_type: flip90
  condition:
    - condition: state
      entity_id: light.ledstrip_veranda
      state: 'on'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.ledstrip_veranda
      effect: >
        {% for x in states.light.ledstrip_veranda.attributes.effect_list %}
          {% if x == states.light.ledstrip_veranda.attributes.effect %}
          {{states.light.ledstrip_veranda.attributes.effect_list[loop.index0-1] }}
          {% endif %}
        {% endfor %}


- alias: "Cube rotate - Veranda ledstrip toggle"
  initial_state: 'on'
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028779a2
      action_type: tap_twice
  action:
  - service: light.toggle
    entity_id: 'light.ledstrip_veranda'





