- alias: 'Test automation on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.testje
      to: 'on'
  action:
    event: temporary_change
    event_data:
      entity_id: light.lampjes_kast
      temporary_start: 1
      brightness: 255
      
- alias: 'Test automation uit'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.testje
      to: 'off'
  action:
    event: temporary_change
    event_data:
      entity_id: light.lampjes_kast
      temporary_start: 0